In [1]:
from pyvis.network import Network
import pandas as pd

In [2]:
pip install palettable

Note: you may need to restart the kernel to use updated packages.


In [3]:
week_keyword = pd.read_excel("../../../../yyaxuan/Documents/repo/TLT_Lab/week_keyword_table_s01_2021.xlsx",index_col=0)
keyword_category = pd.read_excel("../../../../yyaxuan/Documents/repo/TLT_Lab/keyword_category_table.xlsx",index_col=0)

In [4]:
print(week_keyword)
print(keyword_category)

   lasercut  3dprint  woodtool  design  debug  trial  help  2ddesign  measure  \
1         1        1         0       0      1      1     0         0        0   
2         0        0         1       1      1      0     0         0        0   
3         1        0         1       0      1      1     0         1        1   

   angle  shape   material  battery  power  
1      0       0         0        0      0  
2      0       1         1        1      1  
3      1       1         1        0      1  
          category
lasercut         1
3dprint          2
woodtool         3
design           1
debug            4
trial            4
help             4
2ddesign         1
measure          2
angle            4
shape            4
material         4
battery          5
power            5


In [5]:
keywords = list(week_keyword.head())
print(keywords)

['lasercut', '3dprint', 'woodtool', 'design', 'debug', 'trial', 'help', '2ddesign', 'measure', 'angle', 'shape ', 'material', 'battery', 'power']


In [6]:
# the number shows which category the keyword belongs to
keywords_group = keyword_category.iloc[:, 0].to_numpy()
print(keywords_group)

[1 2 3 1 4 4 4 1 2 4 4 4 5 5]


In [7]:
# extract each week's keyword list
week1 = week_keyword.iloc[0].to_numpy()
week2 = week_keyword.iloc[1].to_numpy()
week3 = week_keyword.iloc[2].to_numpy()
print(week1)
print(week2)
print(week3)

[1 1 0 0 1 1 0 0 0 0 0 0 0 0]
[0 0 1 1 1 0 0 0 0 0 1 1 1 1]
[1 0 1 0 1 1 0 1 1 1 1 1 0 1]


In [8]:
# create gradient color for each week's nodes
from palettable.colorbrewer.sequential import Blues_3
palette = Blues_3.hex_colors
print(palette)
palette[0]

['#DEEBF7', '#9ECAE1', '#3182BD']


'#DEEBF7'

In [9]:
net1 = Network(notebook=True, #heading="Individual Knowledge Map Week 1"
              )

# cacluates the number of occurences for each keywork for week 1
occurence_week1 = week_keyword.iloc[:1].sum()
    
for i, value in enumerate(week1):
    if value == 1:
        net1.add_node(i, label=keywords[i], title='Week1',size=(int(occurence_week1[i])+1)*3, color=palette[0])

# show the all node ids we have in the net
net1_id = [dic['id'] for dic in net1.nodes]
print(net1_id)

for i in net1_id:
    for j in net1_id:
        if i != j and keywords_group[i] == keywords_group[j]:
            net1.add_edge(i,j)
            

               
net1.show("social_network1.html")

Local cdn resources have problems on chrome/safari when used in jupyter-notebook. 
[0, 1, 4, 5]


In [10]:
net2 = Network(notebook=True, #heading="Individual Knowledge Map Week 2",
               filter_menu=True,cdn_resources = 'remote')

# cacluates the number of occurences for each keywork for week 1 & week2 in total
occurence_week2 = week_keyword.iloc[:2].sum()
    
for i, value in  enumerate(week1):
    if value == 1:
        net2.add_node(i, label=keywords[i], title='Week1', size=(int(occurence_week2[i])+1)*3, color=palette[0])

for i, value in  enumerate(week2):
    if value == 1:
        net2.add_node(i, label=keywords[i], title='Week2', size=(int(occurence_week2[i])+1)*3, color=palette[1])

# show the all node ids we have in the net
net2_id = [dic['id'] for dic in net2.nodes]
print(net2_id)

for i in net2_id:
    for j in net2_id:
        if i != j and keywords_group[i] == keywords_group[j]:
            net2.add_edge(i,j)
               
net2.show("social_network2.html")

[0, 1, 4, 5, 2, 3, 10, 11, 12, 13]


In [11]:
net3 = Network(notebook=True, #heading="Individual Knowledge Map Week 3",
               filter_menu=True,cdn_resources = 'remote')

# cacluates the number of occurences for each keywork for week 1 & week2 & week3 in total
occurence_week3 = week_keyword.iloc[:2].sum()
    
for i, value in  enumerate(week1):
    if value == 1:
        net3.add_node(i, label=keywords[i], title='Week1',size=(int(occurence_week3[i])+1)*3,color=palette[0])

for i, value in  enumerate(week2):
    if value == 1:
        net3.add_node(i, label=keywords[i], title='Week2',size=(int(occurence_week3[i])+1)*3,color=palette[1])
        
for i, value in  enumerate(week3):
    if value == 1:
        net3.add_node(i, label=keywords[i], title='Week3',size=(int(occurence_week3[i])+1)*3,color=palette[2])

# show the all node ids we have in the net
net3_id = [dic['id'] for dic in net3.nodes]
print(net3_id)

for i in net3_id:
    for j in net3_id:
        if i != j and keywords_group[i] == keywords_group[j]:
            net3.add_edge(i,j)
               
net3.show("social_network3.html")

[0, 1, 4, 5, 2, 3, 10, 11, 12, 13, 7, 8, 9]


In [12]:
################################################################

In [1]:
pip install dash --upgrade

Note: you may need to restart the kernel to use updated packages.


In [1]:
import pandas as pd
import plotly.express as px
from pyvis.network import Network

import dash
from dash import dcc
from dash import html
import dash_bootstrap_components as dbc
import plotly.graph_objs as go
from dash.dependencies import Input, Output, State
import sys
import os

In [2]:
# Create a Dash app
app1 = dash.Dash(__name__, external_stylesheets=[dbc.themes.BOOTSTRAP])

In [3]:
# Define the initial HTML content to display in the Iframe component
initial_html = open('social_network1.html', 'r').read()

In [4]:
with open('social_network2.html', 'r') as f:
    second_html = f.read()
    
with open('social_network3.html', 'r') as f:
    third_html = f.read()

In [5]:
SIDEBAR_STYLE = {
    "position": "fixed",
    "top": 0,
    "left": 0,
    "bottom": 0,
    "width": "25rem",
    "padding": "2rem 1rem",
    "background-color": "rgba(205, 237, 240,  1)",
}

In [6]:
# add some padding.
CONTENT_STYLE = {
    "margin-left": "25rem",
    "margin-right": "0rem",
    "padding": "2rem 1rem",
}

sidebar = html.Div(
    [
        dbc.Row([html.P("Name", className="display-6")]),
        html.Hr(),
        html.P(
            "Knowledge Point Visualization", className="lead"
        ),
        dbc.Nav(
            [
                dbc.NavLink("Individual Graph", href="/", active="exact"),
                dbc.NavLink("Collective Graph", href="/page-1", active="exact"),
                # dbc.NavLink("Collective Graph", href="/page-2", active="exact"),
                #dbc.NavItem(dbc.NavLink('Find a graph by knowledge name:', href='#')),
                #dbc.NavItem(dcc.Input(id='search-bar', type='text', placeholder='Search...')),
        #dbc.NavItem(dbc.NavLink('Link 1', href='#')),
        #dbc.NavItem(dbc.NavLink('Link 2', href='#')),
            ],
            vertical=True,
            pills=True,
        ),
    ],
    style=SIDEBAR_STYLE,
)

In [7]:
div1 = html.Div([html.Iframe(src=app1.get_asset_url("social_network1.html"), style={"width":"100%", "height":"700px"}, id="graph1")], style={"background":"transparent", "height":"700px"})
div2 = html.Div([html.Iframe(src=app1.get_asset_url("social_network2.html"), style={"width":"100%", "height":"700px"}, id="graph2")], style={"background":"transparent", "height":"700px"})
div3 = html.Div([html.Iframe(src=app1.get_asset_url("social_network3.html"), style={"width":"100%", "height":"700px"}, id="graph3")], style={"background":"transparent", "height":"700px"})

content = html.Div(id="page-content", style=CONTENT_STYLE)

In [10]:
# Define the app layout with an Iframe component and a slider bar
app1.layout = html.Div([sidebar, content,
    
    # Dropdown Menu
     #dcc.Dropdown(id='my-dropdown', options=[{'label': 'Individual', 'value': 'option-1'}, {'label': 'Collective', 'value': 'option-2'},{'label': 'Option 3', 'value': 'option-3'}],value='option-1'),
    
    # html.H1(children="Student's Name"),
        # html.P("Show your knowledge point interaction from Week 1 to Week 3"),
    html.Iframe(id='html-iframe', srcDoc=initial_html, style={"position": "absolute", "top": "10px", "right": "50px"}, width="65%",
            height="600"),
    dcc.Link('Go to App 2', href='/app2'),
    html.Br(),
    html.Br(),
dcc.Location(id='url', refresh=False),
    html.Div([
        html.Label('Select a week:'),
        
        dcc.Slider(
            id='my-slider',
          min=0,
            max=2,
            value=1,
            step=1,
        updatemode='drag',
           marks={0: 'Week1', 1: 'Week2', 2: 'Week3'}
        )
    ], style={'width': '65%', 'margin': '450px','margin-top': '500px',
        'color': '#FFFFFF',
        'fontSize': '10px',
        'padding': '5px'})
])

In [9]:
# Add CSS to move the slider to the right side of the screen
#app.css.append_css({
#    '.slider-container': {
#        'position': 'absolute',
#        'bottom': '50px',
 #       'right': '50px'
#    }
#})

In [11]:
# Define the callback function for the slider bar
@app1.callback(Output('page-content', 'children'),
              Input('url', 'pathname'))
def display_page(pathname):
    if pathname == '/app2':
        return dcc.Location(pathname='/app2')
    else:
        return html.Div('Welcome to App 1')

@app1.callback(
    Output('html-iframe', 'srcDoc'),
    Input('my-slider', 'value')
)
def update_output(value):
    # Define the HTML content to display based on the value of the slider bar
    if value == 0:
        return open('social_network1.html', 'r').read()
    elif value == 1:
        return open('social_network2.html', 'r').read()
    elif value == 2:
        return open('social_network3.html', 'r').read()

In [ ]:
# Run the app
if __name__ == '__main__':
    app1.run_server(port=8051)

Dash is running on http://127.0.0.1:8051/

 * Serving Flask app "__main__" (lazy loading)
 * Environment: production
   Use a production WSGI server instead.
 * Debug mode: off


 * Running on http://127.0.0.1:8051/ (Press CTRL+C to quit)
127.0.0.1 - - [09/Mar/2023 00:01:28] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [09/Mar/2023 00:01:28] "GET /_dash-layout HTTP/1.1" 200 -
127.0.0.1 - - [09/Mar/2023 00:01:28] "GET /_dash-dependencies HTTP/1.1" 200 -
127.0.0.1 - - [09/Mar/2023 00:01:28] "GET /_dash-component-suites/dash/dcc/async-slider.js HTTP/1.1" 200 -
127.0.0.1 - - [09/Mar/2023 00:01:28] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [09/Mar/2023 00:01:28] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [09/Mar/2023 00:01:28] "GET /lib/bindings/utils.js HTTP/1.1" 200 -


In [ ]:
###############################################################

In [2]:
external_stylesheets = ['style.css']
app = dash.Dash(__name__, external_stylesheets=external_stylesheets)

In [3]:
app.layout = html.Div([
    html.Nav([
        dcc.Link('Home', href='/', className='nav-link'),
        dcc.Link('About', href='/page-1', className='nav-link'),
        dcc.Link('Instruction', href='/page-2', className='nav-link'),
        dcc.Link('Graph', href='/page-3', className='nav-link'),
    ], className='navbar', style={'display': 'flex', 'justify-content': 'space-between', "background-color": "rgba(205, 237, 240,  1)", "padding": "1rem", 'align-items': 'center'}),
    html.Br(),
    dcc.Location(id='url', refresh=False),
    html.Div(id='page-content')
])

In [4]:
@app.callback(Output('page-content', 'children'),
              [Input('url', 'pathname')])
def display_page(pathname):
    if pathname == '/':
        return html.H1('Home')
    elif pathname == '/page-1':
        return html.H1('About')
    elif pathname == '/page-2':
        return html.H1('Instruction')
    elif pathname == '/page-3':
        return html.H1('Graph')
    else:
        return html.H1('404 - Page not found')

In [5]:
if __name__ == '__main__':
    app.run_server(port=8052)

Dash is running on http://127.0.0.1:8052/

 * Serving Flask app "__main__" (lazy loading)
 * Environment: production
   Use a production WSGI server instead.
 * Debug mode: off


 * Running on http://127.0.0.1:8052/ (Press CTRL+C to quit)
127.0.0.1 - - [08/Mar/2023 23:52:42] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [08/Mar/2023 23:52:42] "GET /style.css HTTP/1.1" 200 -
127.0.0.1 - - [08/Mar/2023 23:52:43] "GET /_dash-layout HTTP/1.1" 200 -
127.0.0.1 - - [08/Mar/2023 23:52:43] "GET /_dash-dependencies HTTP/1.1" 200 -
127.0.0.1 - - [08/Mar/2023 23:52:43] "POST /_dash-update-component HTTP/1.1" 200 -


In [2]:
# Define the first app
app1 = dash.Dash(__name__)
app1.layout = html.Div([
    html.H1('App 1'),
    dcc.Link('Go to App 2', href='/app2'),
    html.Br(),
    dcc.Location(id='url', refresh=False),
    html.Div(id='page-content')
])

@app1.callback(Output('page-content', 'children'),
              Input('url', 'pathname'))
def display_page(pathname):
    if pathname == '/app2':
        return dcc.Location(pathname='/app2')
    else:
        return html.Div('Welcome to App 1')

In [3]:
# Define the second app
app2 = dash.Dash(__name__)
app2.layout = html.Div([
    html.H1('App 2'),
    dcc.Link('Go to App 1', href='/app1'),
    html.Br(),
    dcc.Location(id='url', refresh=False),
    html.Div(id='page-content')
])

@app2.callback(Output('page-content', 'children'),
              Input('url', 'pathname'))
def display_page(pathname):
    if pathname == '/app1':
        return dcc.Location(pathname='/app1')
    else:
        return html.Div('Welcome to App 2')

In [4]:
# Combine the two apps into one app
server = app1.server
app1.title = 'My Linked Apps'
app1.config.suppress_callback_exceptions = True

In [5]:

if __name__ == '__main__':
    app1.run_server(port=8053)

Dash is running on http://127.0.0.1:8053/

Dash is running on http://127.0.0.1:8053/

 * Serving Flask app "__main__" (lazy loading)
 * Environment: production
   Use a production WSGI server instead.
 * Debug mode: off


 * Running on http://127.0.0.1:8053/ (Press CTRL+C to quit)
127.0.0.1 - - [08/Mar/2023 23:56:15] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [08/Mar/2023 23:56:15] "GET /_dash-component-suites/dash/deps/polyfill@7.v2_8_1m1677342896.12.1.min.js HTTP/1.1" 200 -
127.0.0.1 - - [08/Mar/2023 23:56:15] "GET /_dash-component-suites/dash/deps/react@16.v2_8_1m1677342896.14.0.min.js HTTP/1.1" 200 -
127.0.0.1 - - [08/Mar/2023 23:56:15] "GET /_dash-component-suites/dash/deps/react-dom@16.v2_8_1m1677342896.14.0.min.js HTTP/1.1" 200 -
127.0.0.1 - - [08/Mar/2023 23:56:15] "GET /_dash-component-suites/dash/deps/prop-types@15.v2_8_1m1677342896.8.1.min.js HTTP/1.1" 200 -
127.0.0.1 - - [08/Mar/2023 23:56:15] "GET /_dash-component-suites/dash_bootstrap_components/_components/dash_bootstrap_components.v1_4_0m1678040315.min.js HTTP/1.1" 200 -
127.0.0.1 - - [08/Mar/2023 23:56:16] "GET /_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_8_1m1677342896.min.js HTTP/1.1" 200 -
127.0.0.1 - - [08/Mar/2023 23

Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "/Users/yyaxuan/opt/anaconda3/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yyaxuan/opt/anaconda3/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yyaxuan/opt/anaconda3/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/yyaxuan/opt/anaconda3/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/yyaxuan/opt/anaconda3/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yyaxuan/opt/anaconda3/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/yyaxuan/

127.0.0.1 - - [08/Mar/2023 23:56:17] "POST /_dash-update-component HTTP/1.1" 500 -
127.0.0.1 - - [08/Mar/2023 23:56:29] "POST /_dash-update-component HTTP/1.1" 200 -


Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "/Users/yyaxuan/opt/anaconda3/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yyaxuan/opt/anaconda3/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yyaxuan/opt/anaconda3/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/yyaxuan/opt/anaconda3/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/yyaxuan/opt/anaconda3/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yyaxuan/opt/anaconda3/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/yyaxuan/

127.0.0.1 - - [08/Mar/2023 23:56:30] "POST /_dash-update-component HTTP/1.1" 500 -
