In [1]:
from pyvis.network import Network
import pandas as pd

In [2]:
pip install palettable

Note: you may need to restart the kernel to use updated packages.


In [3]:
week_keyword = pd.read_excel("../../../../yyaxuan/Documents/repo/TLT_Lab/week_keyword_table_s01_2021.xlsx",index_col=0)
keyword_category = pd.read_excel("../../../../yyaxuan/Documents/repo/TLT_Lab/keyword_category_table.xlsx",index_col=0)

In [4]:
print(week_keyword)
print(keyword_category)

   lasercut  3dprint  woodtool  design  debug  trial  help  2ddesign  measure  \
1         1        1         0       0      1      1     0         0        0   
2         0        0         1       1      1      0     0         0        0   
3         1        0         1       0      1      1     0         1        1   

   angle  shape   material  battery  power  
1      0       0         0        0      0  
2      0       1         1        1      1  
3      1       1         1        0      1  
          category
lasercut         1
3dprint          2
woodtool         3
design           1
debug            4
trial            4
help             4
2ddesign         1
measure          2
angle            4
shape            4
material         4
battery          5
power            5


In [5]:
keywords = list(week_keyword.head())
print(keywords)

['lasercut', '3dprint', 'woodtool', 'design', 'debug', 'trial', 'help', '2ddesign', 'measure', 'angle', 'shape ', 'material', 'battery', 'power']


In [6]:
# the number shows which category the keyword belongs to
keywords_group = keyword_category.iloc[:, 0].to_numpy()
print(keywords_group)

[1 2 3 1 4 4 4 1 2 4 4 4 5 5]


In [7]:
# extract each week's keyword list
week1 = week_keyword.iloc[0].to_numpy()
week2 = week_keyword.iloc[1].to_numpy()
week3 = week_keyword.iloc[2].to_numpy()
print(week1)
print(week2)
print(week3)

[1 1 0 0 1 1 0 0 0 0 0 0 0 0]
[0 0 1 1 1 0 0 0 0 0 1 1 1 1]
[1 0 1 0 1 1 0 1 1 1 1 1 0 1]


In [8]:
# create gradient color for each week's nodes
from palettable.colorbrewer.sequential import Blues_3
palette = Blues_3.hex_colors
print(palette)
palette[0]

['#DEEBF7', '#9ECAE1', '#3182BD']


'#DEEBF7'

In [9]:
net1 = Network(notebook=True, #heading="Individual Knowledge Map Week 1"
              )

# cacluates the number of occurences for each keywork for week 1
occurence_week1 = week_keyword.iloc[:1].sum()
    
for i, value in enumerate(week1):
    if value == 1:
        net1.add_node(i, label=keywords[i], title='Week1',size=(int(occurence_week1[i])+1)*3, color=palette[0])

# show the all node ids we have in the net
net1_id = [dic['id'] for dic in net1.nodes]
print(net1_id)

for i in net1_id:
    for j in net1_id:
        if i != j and keywords_group[i] == keywords_group[j]:
            net1.add_edge(i,j)
            

               
net1.show("social_network1.html")

[0, 1, 4, 5]
social_network1.html


In [10]:
net2 = Network(notebook=True, #heading="Individual Knowledge Map Week 2",filter_menu=True,
               cdn_resources = 'remote')

# cacluates the number of occurences for each keywork for week 1 & week2 in total
occurence_week2 = week_keyword.iloc[:2].sum()
    
for i, value in  enumerate(week1):
    if value == 1:
        net2.add_node(i, label=keywords[i], title='Week1', size=(int(occurence_week2[i])+1)*3, color=palette[0])

for i, value in  enumerate(week2):
    if value == 1:
        net2.add_node(i, label=keywords[i], title='Week2', size=(int(occurence_week2[i])+1)*3, color=palette[1])

# show the all node ids we have in the net
net2_id = [dic['id'] for dic in net2.nodes]
print(net2_id)

for i in net2_id:
    for j in net2_id:
        if i != j and keywords_group[i] == keywords_group[j]:
            net2.add_edge(i,j)
               
net2.show("social_network2.html")

[0, 1, 4, 5, 2, 3, 10, 11, 12, 13]
social_network2.html


In [11]:
net3 = Network(notebook=True, #heading="Individual Knowledge Map Week 3", filter_menu=True,
               cdn_resources = 'remote')

# cacluates the number of occurences for each keywork for week 1 & week2 & week3 in total
occurence_week3 = week_keyword.iloc[:2].sum()
    
for i, value in  enumerate(week1):
    if value == 1:
        net3.add_node(i, label=keywords[i], title='Week1',size=(int(occurence_week3[i])+1)*3,color=palette[0])

for i, value in  enumerate(week2):
    if value == 1:
        net3.add_node(i, label=keywords[i], title='Week2',size=(int(occurence_week3[i])+1)*3,color=palette[1])
        
for i, value in  enumerate(week3):
    if value == 1:
        net3.add_node(i, label=keywords[i], title='Week3',size=(int(occurence_week3[i])+1)*3,color=palette[2])

# show the all node ids we have in the net
net3_id = [dic['id'] for dic in net3.nodes]
print(net3_id)

for i in net3_id:
    for j in net3_id:
        if i != j and keywords_group[i] == keywords_group[j]:
            net3.add_edge(i,j)
               
net3.show("social_network3.html")

[0, 1, 4, 5, 2, 3, 10, 11, 12, 13, 7, 8, 9]
social_network3.html


In [12]:
################################################################

In [ ]:
pip install dash --upgrade

In [1]:
import pandas as pd
import plotly.express as px
from pyvis.network import Network

import dash
from dash import dcc
from dash import html
import dash_bootstrap_components as dbc
import plotly.graph_objs as go
from dash.dependencies import Input, Output, State
import sys
import os

In [2]:
# Create a Dash app
app = dash.Dash(__name__, external_stylesheets=[dbc.themes.BOOTSTRAP])

In [3]:
# Define the initial HTML content to display in the Iframe component
initial_html = open('social_network1.html', 'r').read()

In [4]:
with open('social_network2.html', 'r') as f:
    second_html = f.read()
    
with open('social_network3.html', 'r') as f:
    third_html = f.read()

In [5]:
SIDEBAR_STYLE = {
    "position": "fixed",
    "top": 0,
    "left": 0,
    "bottom": 0,
    "width": "25rem",
    "padding": "2rem 1rem",
    "background-color": "rgba(205, 237, 240,  1)",
}

In [8]:
# add some padding.
CONTENT_STYLE = {
    "margin-left": "25rem",
    "margin-right": "0rem",
    "padding": "2rem 1rem",
}

sidebar = html.Div(
    [
        dbc.Row([html.P("Name", className="display-6")]),
        html.Hr(),
        html.P(
            "Knowledge Point Visualization", className="lead"
        ),
        dbc.Nav(
            [
                dbc.NavLink("Individual Graph", href="/", active="exact"),
                dbc.NavLink("Collective Graph", href="/page-1", active="exact"),
                dbc.NavLink("About", href="/page-2", active="exact")
            ],
            vertical=True,
            pills=True,
        ),
    ],
    style=SIDEBAR_STYLE,
)

In [ ]:
div1 = html.Div([html.Iframe(src=app.get_asset_url("social_network1.html"), style={"width":"100%", "height":"700px"}, id="graph1")], style={"background":"transparent", "height":"700px"})
div2 = html.Div([html.Iframe(src=app.get_asset_url("social_network2.html"), style={"width":"100%", "height":"700px"}, id="graph2")], style={"background":"transparent", "height":"700px"})
div3 = html.Div([html.Iframe(src=app.get_asset_url("social_network3.html"), style={"width":"100%", "height":"700px"}, id="graph3")], style={"background":"transparent", "height":"700px"})

content = html.Div(id="page-content", style=CONTENT_STYLE)

In [ ]:
# Define the app layout with an Iframe component and a slider bar
app_layout = html.Div([sidebar, content,
    html.Iframe(id='html-iframe', srcDoc=initial_html, style={"position": "absolute", "top": "10px", "right": "50px"}, width="65%",
            height="600"),
    html.Br(),
    html.Br(),
    html.Div([
        html.Label('Select a week:'),
        
        dcc.Slider(
            id='my-slider',
          min=0,
            max=2,
            value=1,
            step=1,
        updatemode='drag',
           marks={0: 'Week1', 1: 'Week2', 2: 'Week3'}
        )
    ], style={'width': '65%', 'margin': '450px','margin-top': '500px',
        'color': '#FFFFFF',
        'fontSize': '10px',
        'padding': '5px'})
])

In [9]:
# Define the page layout for page 1
page1_layout = html.Div(
    children=[
        html.H1("This is Page 1"),
        html.P("Welcome to Page 1!")
    ]
)

# Define the page layout for page 2
#page2_layout = html.Div(
#    children=[
#        html.H1("This is Page 2"),
#        html.P("Welcome to Page 2!")
#    ]
#)

In [10]:
# Define the app layout
app.layout = html.Div(
    children=[
        current_layout,
        html.Div(id="page-content")
    ]
)

In [11]:
# Define the callback to update the page content based on the URL and button click
@app.callback(
    [Output("page-content", "children"), Output("current-layout", "data")],
    [Input("url", "pathname"), Input("go-to-new-page", "n_clicks")],
    [State("current-layout", "data")]

In [ ]:
def display_page(pathname, n_clicks, current_layout):
    # Default to home layout
    new_layout = app.layout

    # Update the layout if the button is clicked
    if n_clicks:
        new_layout = new_layout

    # Return the new layout and update the current layout
    return new_layout, new_layout

In [12]:
# Define the callback function for the slider bar
@app.callback(
    Output('html-iframe', 'srcDoc'),
    Input('my-slider', 'value')
)
def update_output(value):
    # Define the HTML content to display based on the value of the slider bar
    if value == 0:
        return open('social_network1.html', 'r').read()
    elif value == 1:
        return open('social_network2.html', 'r').read()
    elif value == 2:
        return open('social_network3.html', 'r').read()

In [13]:
@app.callback(Output('page-content', 'children'),
              [Input('url', 'pathname')])
def display_page(pathname):
    time.sleep(2) # simulate a delay in loading the page
    if pathname == '/page-1':
        return page1_layout
    elif pathname == '/page-2':
        return page2_layout
    else:
        return html.Div("404 Page not found")

In [15]:
# Run the app
if __name__ == '__main__':
    app.run_server(port=8056)

Dash is running on http://127.0.0.1:8056/

 * Serving Flask app "__main__" (lazy loading)
 * Environment: production
   Use a production WSGI server instead.
 * Debug mode: off


 * Running on http://127.0.0.1:8056/ (Press CTRL+C to quit)
127.0.0.1 - - [09/Mar/2023 16:15:56] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [09/Mar/2023 16:15:56] "GET /_dash-layout HTTP/1.1" 200 -
127.0.0.1 - - [09/Mar/2023 16:15:56] "GET /_dash-dependencies HTTP/1.1" 200 -
127.0.0.1 - - [09/Mar/2023 16:15:56] "GET /_dash-component-suites/dash/dcc/async-slider.js HTTP/1.1" 200 -
127.0.0.1 - - [09/Mar/2023 16:15:56] "GET /lib/bindings/utils.js HTTP/1.1" 200 -
127.0.0.1 - - [09/Mar/2023 16:15:56] "POST /_dash-update-component HTTP/1.1" 200 -


In [ ]:
#########################################################

In [1]:
import pandas as pd
import plotly.express as px
from pyvis.network import Network

import dash
from dash import dcc
from dash import html
import dash_bootstrap_components as dbc
import plotly.graph_objs as go
from dash.dependencies import Input, Output, State
import sys
import os

In [2]:
# Initialize the app
app = dash.Dash(__name__)

# Define the sidebar content
sidebar = html.Nav(
    className="sidebar",
    children=[
        html.Ul(
            className="nav-menu",
            children=[
                html.Li(html.A("Home", href="/")),
                html.Li(html.A("Page 1", href="/page1")),
                html.Li(html.A("Page 2", href="/page2"))
            ]
        )
    ]
)

# Define the home layout
home_layout = html.Div(
    className="content",
    children=[
        html.H1("Welcome to the Home Page")
    ]
)

# Define the app layout
app.layout = html.Div(
    children=[
        sidebar,
        html.Div(
            className="main-content",
            children=[
                dcc.Location(id="url", refresh=False),
                html.Div(id="page-content")
            ]
        )
    ]
)

In [3]:
# add some padding.
CONTENT_STYLE = {
    "margin-left": "25rem",
    "margin-right": "0rem",
    "padding": "2rem 1rem",
}

In [4]:
div1 = html.Div([html.Iframe(src=app.get_asset_url("social_network1.html"), style={"width":"100%", "height":"700px"}, id="graph1")], style={"background":"transparent", "height":"700px"})
div2 = html.Div([html.Iframe(src=app.get_asset_url("social_network2.html"), style={"width":"100%", "height":"700px"}, id="graph2")], style={"background":"transparent", "height":"700px"})
div3 = html.Div([html.Iframe(src=app.get_asset_url("social_network3.html"), style={"width":"100%", "height":"700px"}, id="graph3")], style={"background":"transparent", "height":"700px"})

content = html.Div(id="page-content", style=CONTENT_STYLE)

In [5]:
# Define the initial HTML content to display in the Iframe component
initial_html = open('social_network1.html', 'r').read()

In [6]:
with open('social_network2.html', 'r') as f:
    second_html = f.read()
    
with open('social_network3.html', 'r') as f:
    third_html = f.read()

In [7]:
# Define the app layout with an Iframe component and a slider bar
page1_layout = html.Div([content,
    html.Iframe(id='html-iframe', srcDoc=initial_html, style={"position": "absolute", "top": "10px", "right": "50px"}, width="65%",
            height="600"),
    html.Br(),
    html.Br(),
    html.Div([
        html.Label('Select a week:'),
        
        dcc.Slider(
            id='my-slider',
          min=0,
            max=2,
            value=1,
            step=1,
        updatemode='drag',
           marks={0: 'Week1', 1: 'Week2', 2: 'Week3'}
        )
    ], style={'width': '65%', 'margin': '450px','margin-top': '500px',
        'color': '#FFFFFF',
        'fontSize': '10px',
        'padding': '5px'})
])

In [8]:
# Define the callback function for the slider bar
@app.callback(
    Output('html-iframe', 'srcDoc'),
    Input('my-slider', 'value')
)
def update_output(value):
    # Define the HTML content to display based on the value of the slider bar
    if value == 0:
        return open('social_network1.html', 'r').read()
    elif value == 1:
        return open('social_network2.html', 'r').read()
    elif value == 2:
        return open('social_network3.html', 'r').read()

In [ ]:
# Define the callback to update the page content based on the URL
@app.callback(dash.dependencies.Output("page-content", "children"), [dash.dependencies.Input("url", "pathname")])
def display_page(pathname):
    if pathname == "/page1":
        return page1_layout
        #return html.H1("This is Page 1")
    elif pathname == "/page2":
        return html.H1("This is Page 2")
    else:
        return home_layout

# Run the app
if __name__ == '__main__':
    app.run_server(port=8057)

Dash is running on http://127.0.0.1:8057/

 * Serving Flask app "__main__" (lazy loading)
 * Environment: production
   Use a production WSGI server instead.
 * Debug mode: off


 * Running on http://127.0.0.1:8057/ (Press CTRL+C to quit)
127.0.0.1 - - [09/Mar/2023 16:39:35] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [09/Mar/2023 16:39:36] "GET /_dash-layout HTTP/1.1" 200 -
127.0.0.1 - - [09/Mar/2023 16:39:36] "GET /_dash-dependencies HTTP/1.1" 200 -
127.0.0.1 - - [09/Mar/2023 16:39:36] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [09/Mar/2023 16:39:37] "GET /page1 HTTP/1.1" 200 -
127.0.0.1 - - [09/Mar/2023 16:39:37] "GET /_dash-layout HTTP/1.1" 200 -
127.0.0.1 - - [09/Mar/2023 16:39:37] "GET /_dash-dependencies HTTP/1.1" 200 -
127.0.0.1 - - [09/Mar/2023 16:39:37] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [09/Mar/2023 16:39:37] "GET /_dash-component-suites/dash/dcc/async-slider.js HTTP/1.1" 200 -
127.0.0.1 - - [09/Mar/2023 16:39:37] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [09/Mar/2023 16:39:37] "GET /lib/bindings/utils.js HTTP/1.1" 200 -
127.0.0.1 - - [09/Mar/2023 16:39:56] "GET /page2 HTTP/1.1" 200 -
127.0.0.1 - -